document.write(`
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LED Scrolling Text</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        background-color: black;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        overflow: hidden;
      }
      .led-text {
        color: white;
        font-size: calc(30vw + 30px);
        font-family: 'Courier New', Courier, monospace;
        font-weight: 900;
        white-space: nowrap;
        animation: scroll 15s linear infinite;
      }
      @keyframes scroll {
        0% {
          transform: translateX(100%);
        }
        100% {
          transform: translateX(-100%);
        }
      }
    </style>
  </head>
  <body>
    <div class="led-text">yoko malisorn; faye 不知道了</div>
  </body>
  </html>
`);
